### ISSUE TITLE
3.1.4 not working on rpi3 

### ISSUE THREAD

**Issue by riddertommie** [frbncis/docker-arm32v7-omada#8]
I tried installing with 

sudo docker run -d --net=host --restart=always frnby/omada-eap-controller:3.1.4

But container gets unhealthy and loops with the same error over en over again

startup...
May 24, 2019 10:40:28 AM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 4.3.1.Final
Failed to start omada controller, going to exit
ShutdownHook: service stopped.

Any tips/hints?

Thanks

**Comment by jeremyhiggs** [comment]
This happens with 3.2.1 as well:

> startup...,
> Dec 15, 2019 10:11:00 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> startup...,
> Dec 15, 2019 10:15:30 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> SLF4J: com.tp_link.eap.util.m.a,
> SLF4J: The following set of substitute loggers may have been accessed,
> SLF4J: during the initialization phase. Logging calls during this,
> SLF4J: phase were not honored. However, subsequent logging calls to these,
> SLF4J: loggers will work as normally expected.,
> SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger,
> SLF4J: com.tp_link.eap.util.m.a,
> startup...,
> Dec 15, 2019 10:19:58 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> SLF4J: com.tp_link.eap.util.m.a,
> SLF4J: The following set of substitute loggers may have been accessed,
> SLF4J: during the initialization phase. Logging calls during this,
> SLF4J: phase were not honored. However, subsequent logging calls to these,
> SLF4J: loggers will work as normally expected.,
> SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger,
> SLF4J: com.tp_link.eap.util.m.a,
> startup...,
> Dec 15, 2019 10:24:29 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> SLF4J: com.tp_link.eap.util.m.a,
> SLF4J: The following set of substitute loggers may have been accessed,
> SLF4J: during the initialization phase. Logging calls during this,
> SLF4J: phase were not honored. However, subsequent logging calls to these,
> SLF4J: loggers will work as normally expected.,
> SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger,
> Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical,
> 	at java.io.File.<init>(File.java:418),
> 	at com.tp_link.eap.util.g.a.a(SourceFile:47),
> 	at com.tp_link.eap.configuration.b.a(SourceFile:58),
> 	at com.tp_link.eap.util.o.c(SourceFile:443),
> 	at com.tp_link.eap.util.o.b(SourceFile:434),
> 	at com.tp_link.eap.start.f.run(SourceFile:35),
> startup...,
> Dec 15, 2019 10:29:01 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical,
> 	at java.io.File.<init>(File.java:418),
> 	at com.tp_link.eap.util.g.a.a(SourceFile:47),
> 	at com.tp_link.eap.configuration.b.a(SourceFile:58),
> 	at com.tp_link.eap.util.o.c(SourceFile:443),
> 	at com.tp_link.eap.util.o.b(SourceFile:434),
> 	at com.tp_link.eap.start.f.run(SourceFile:35),
> startup...,
> Dec 15, 2019 10:33:32 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> startup...,
> Dec 15, 2019 10:38:02 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical,
> 	at java.io.File.<init>(File.java:418),
> 	at com.tp_link.eap.util.g.a.a(SourceFile:47),
> 	at com.tp_link.eap.configuration.b.a(SourceFile:58),
> 	at com.tp_link.eap.util.o.c(SourceFile:443),
> 	at com.tp_link.eap.util.o.b(SourceFile:434),
> 	at com.tp_link.eap.start.f.run(SourceFile:35),
> startup...,
> Dec 15, 2019 10:42:34 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> SLF4J: com.tp_link.eap.util.m.a,
> SLF4J: The following set of substitute loggers may have been accessed,
> SLF4J: during the initialization phase. Logging calls during this,
> SLF4J: phase were not honored. However, subsequent logging calls to these,
> SLF4J: loggers will work as normally expected.,
> SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger,
> Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical,
> 	at java.io.File.<init>(File.java:418),
> 	at com.tp_link.eap.util.g.a.a(SourceFile:47),
> 	at com.tp_link.eap.configuration.b.a(SourceFile:58),
> 	at com.tp_link.eap.util.o.c(SourceFile:443),
> 	at com.tp_link.eap.util.o.b(SourceFile:434),
> 	at com.tp_link.eap.start.f.run(SourceFile:35),
> startup...,
> Dec 15, 2019 10:47:06 AM org.hibernate.validator.internal.util.Version <clinit>,
> INFO: HV000001: Hibernate Validator 4.3.1.Final,
> Failed to start omada controller, going to exit,
> ShutdownHook: service stopped.,
> startup...,

Eventually it does start. Is there anything we can do to diagnose the cause of the problem?

**Comment by jeremyhiggs** [comment]
Similar issue here: https://github.com/mbentley/docker-omada-controller/issues/6

In my case, I have the "db" folder already. Omada does eventually start, it's just flakey.

**Comment by timdonovanuk** [comment]
FWIW I see this issue on x64 architecture. I have created the db dir, chowned it to 508 etc.
